name: Test
on:
  push:
    branches:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm ci
        npm run build
        npm run test